co2_emission = {
    'SPICES': [17],
    'LABELS': [51],
    'METAL': [23],
    'BARRELS': [9],
    'SLICED BEEF': [57, 38],
    'FASSS': [9],
    'PEPPER': [17],
    'BEAN': [10],
    'TOMATO': [75],
    'METAL LATCH': [23],
    'FROZEN FRUIT': [75],
    'GLASS JAR': [29],
    'BEEF CUTTER': [23],
    'PRESERVED VEGETABLE': [75],
    'PORK SLICED': [38],
    'MEAT': [35],
    'SELF-ADHESIVE LABELS': [51],
    'PLASTIC BOTTLES ARE': [53],
    'METAL CLOSURE': [23],
    'BEARING CONSUMERS': [23],
    'PLAST IC': [53],
    'PROCESSED PORK': [38],
    'RICE': [10],
    'KEGS': [9],
    'STOCK CONSUMERS': [24],
    'CORN': [10],
    'BEEF CUT': [57, 38],
    'GARLIC': [75],
    'RAPE SEED OIL': [58],
    'ALUMINUM': [3],
    'ADHESIVE LABELS': [51],
    'PLASTIC CAP': [53],
    'PRESERVED VEGETABLES': [75],
    'ESTABLISH LABEL': [51],
    'PLASTIC BOTTLES': [53],
    'BEEF SLICED': [57, 38],
    'PORK CUT': [38],
    'GLASS VESSEL': [29],
    'LABEL': [51],
    'CUCUMBER': [75],
    'LETTERING': [56],
    'CRYSTAL SUGAR': [71],
    'BARREL': [9]}

'''
'': [None],
'WAREHOUSE CONSUMERS': [None],
'FEGOKK': [None],
'''
